using MySTL;
using System.ComponentModel;
using System.Diagnostics;

var tree = new MyTree();
tree.Insert(44);
tree.Insert(17);
tree.Insert(88);
tree.Insert(32);
tree.Insert(28);
tree.Insert(29);
tree.Insert(97);
tree.Insert(65);
tree.Insert(54);
tree.Insert(82);
tree.Insert(76);
tree.Insert(80);
tree.Insert(78);
tree.Remove(32);
tree.Remove(65);
Console.WriteLine();